### ISSUE TITLE
correct ESP-CAM SW to use

### ISSUE THREAD

**Issue by Mackalope** [CyberSensei1/OctoPrint-Esp32CamUI#3]
I set up my ESP using the following https://github.com/Linkenelis/ESP32-cam-Octoprint, and doesn't seem to work with this plugin. What ESP32-CAM SW should I run with this plugin?

**Comment by CyberSensei1** [comment]
Hi,
Our plugin adds a new tab to OctoPrint that displays any URL. I looked at this repo, but it does not have a user interface for the ESP32-Cam codes. Therefore, if you set your IP in our plugin, you won't be able to see anything because there is no user interface for your IP/installation.

A great user interface for the ESP32-Cam can be found at https://github.com/easytarget/esp32-cam-webserver. You can install it on your board and then set the Stream URL and Snapshot URL in OctoPrint's webcam settings as follows:
Stream URL: http://ESP32-CAM-IP:81/
Snapshot URL: http://ESP32-CAM-IP/capture
